version: '3.8'

services:
  trackwithak:
    build: .
    ports:
      - "8080:8080"
    environment:
      - bot=${BOT_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
